### ISSUE TITLE
Odd behaviours with Craft 3.7.0

### ISSUE THREAD

**Issue by nickdunn** [engram-design/Workflow#133]
**Description**
In Craft 3.7.0 we're seeing some odd behaviour, so this maybe several issues in one report.

1. When a user creates a new piece of content and sends for approval, it appears in the workflow twice:

<img width="1189" alt="Screenshot 2021-07-15 at 13 41 10" src="https://user-images.githubusercontent.com/39560/125789820-444747f8-5a44-40ff-a7fd-0dd4e1357112.png">

<img width="410" alt="Screenshot 2021-07-15 at 13 42 57" src="https://user-images.githubusercontent.com/39560/125789888-2ba78e02-3d4d-4b7c-a15b-3ec7ac861e03.png">

The first row has a URL of `/entries/page/33607-nick-test-page-please-ignore` and the other `/entries/page/33607-nick-test-page-please-ignore?draftId=473`. I'm not sure if it used to do this.

2. If I then make another change to the entry (e.g. edit its title) a new draft is auto-saved. If I refresh the entry form, then my "awaiting approval" box changes to "Submit for review", presumably because I can now send this draft to supersede the first one.

I submit this second for approval. When the page reloads, the "Submit for review" for is still present and it doesn't say "awaiting approval" any more. When I try to edit a field, Craft shows me an error icon as the AJAX response is that the entry has been sent for review.

<img width="1679" alt="Screenshot 2021-07-15 at 13 49 07" src="https://user-images.githubusercontent.com/39560/125790789-1986aacf-eda7-4c3f-8a4c-3ef8dfe5317e.png">

3. On the approver's side I'm not consistently seeing the panel to enter a comment and approve. In step 1 above, for both of those entries listed in the workflow table, when I view those entries as an approver I don't see any workflow panel at all.

For example two edits here for a page title:

<img width="344" alt="Screenshot 2021-07-15 at 13 55 13" src="https://user-images.githubusercontent.com/39560/125791632-e1961b15-add9-4165-92b3-c45552b93ba2.png">

But when I click on each (both have URL `/entries/page/7?draftId=470`) I don't see the workflow panel:

<img width="1542" alt="Screenshot 2021-07-15 at 13 55 24" src="https://user-images.githubusercontent.com/39560/125791710-834613a1-c5eb-466f-82ab-00b297cd116e.png">

Having played around with this, I think it may be related to entires created before and after 3.7. When making edits of old entries and sending for approval, the approver doesn't see the workflow panel. But they do see it for new entries created post-upgrade.

**Additional info**
- Plugin version: 1.5.9
- Craft version: 3.7.0
- Multi-site: No

**Comment by engram-design** [comment]
Yep, there are some known issues in 3.7+ due to how the authoring experience has changed. It'll require a bit of re-working which we're working on now. I'll keep you updated, but will be ASAP.

**Comment by engram-design** [comment]
Should be fixed in [1.6.0](https://github.com/verbb/workflow/releases/tag/1.6.0)

**Comment by nickdunn** [comment]
Thanks for looking at this so quickly! 

I'm afraid I'm still seeing the issues above using Craft 3.7.3.2 and Workflow 1.6.0.

Things work for all-new entries, but any existing entry still exhibits the same issues.

1. As an editor, go to an existing entry.
2. Make a change and submit draft for review
3. The entry doesn't go into "locked" state
4. The submission appears in the Workflow pending table
5. As an approver, go to the entry but don't see the panel on the right hand side

**Comment by nickdunn** [comment]
I also see an issue in all-new entries where:

1. As an editor create a new entry
2. Submit for review with a note and see it go into "Awaiting approval" state
3. Come back to the entry again and start typing into a field
4. See the Craft AJAX spinner next to the title become exclamation mark "Your changes could not be saved."

I know this is because the entry is locked for approval, but I would have expected a slightly cleaner experience here. Perhaps a feature improvement and not a bug.

**Comment by leightonhughes** [comment]
Thanks for that 1.6.0 fix Josh. I'm still seeing issues with existing entries also.

**Comment by engram-design** [comment]
@nickdunn I'll dive back into this as I thought I'd covered off all scenarios.

As for your second point, there's not a whole lot we can do here to prevent Craft's auto-saving behaviour. So at the moment, that's the best we have.

**Comment by nickdunn** [comment]
Thanks 🤞 

> As for your second point, there's not a whole lot we can do here to prevent Craft's auto-saving behaviour. So at the moment, that's the best we have.

Yeah, fair enough :-)

**Comment by engram-design** [comment]
Just pushed a fix for this if you're able to verify. Change your `verbb/workflow` requirement in `composer.json` to:

```
"require": {
  "verbb/workflow": "dev-craft-3 as 1.6.0",
  "...": "..."
}
```

Then run `composer update`.

**Comment by nickdunn** [comment]
Thank you! I'm afraid I'm just about to disappear on vacation for a week but hopefully someone else can validate this too CC @leightonhughes

**Comment by leightonhughes** [comment]
Working with my client now. Thanks for that Josh!

**Comment by engram-design** [comment]
Thanks for confirming @leightonhughes fixed in [1.6.1](https://github.com/verbb/workflow/releases/tag/1.6.1)
