### ISSUE TITLE
Front end submissions throwing integrity constraint error

### ISSUE THREAD

**Issue by mark-adigital** [engram-design/Workflow#56]
Hi,

I've just updated a dev site running this plugin to Craft 3.1.16 and Workflow 1.1.6, however the implementation required is not straightforward and I think the changes made to front-end submissions has introduced a conflict. In this case, Workflow submissions are made through a front-end entry form that creates or updates a single draft, and if a draft exists then a separate button is displayed to trigger the approval request, however editors also have the option to keep updating that same draft after requesting approval.

Establishing exactly how this process should work with the client around their requirements and how Workflow worked previously was far from straightforward, so I'd prefer to try and preserve that process with the new updates if possible - it would mean re-opening a major can of worms for us to change it.

The specific problem I'm having is that when submitting the approval request via a link with the href `/actions/workflow/submissions/save-submission&entryId={{ entry.id }}&draftId={{ entry.draftId }}&siteId={{ currentSite.id }}&ownerId={{ currentUser.id }}`, the error 'Integrity constraint violation: 1048 Column 'ownerId' cannot be null' is thrown, however the request does still seem to be created. Additionally, when responding as a publisher the editor doesn't receive the email notification - and I'm guessing these two issues are probably related.

I know you have documentation at:  https://verbb.io/craft-plugins/workflow/docs/template-guides/front-end-submission around front end submission, but given the added complications here I wanted to get your take on the best way to achieve this specific process please.

Ironically, I was aware of these potentially breaking changes but the main reason I performed these updates was to see if a different issue was addressed - prior to updating the editor email notifications were stuck using the default format despite me having updated this in the Craft CP. It's possible the updates will resolve that issue but obviously I haven't been able to test it yet.

Sorry for the mini-essay and thank you for any help you can provide!

Mark

**Comment by engram-design** [comment]
Yep, so Workflow didn't really support having these action endpoints triggered via a URL as you supplied, and expected a POST request.

This should be fixed in [1.1.7](https://github.com/verbb/workflow/releases/tag/1.1.7)

**Comment by mark-adigital** [comment]
Brilliant, can confirm this has resolved the problem with creating submissions - thank you! I'm still not receiving the editor notification emails however, but can open a separate issue for that.

**Comment by mark-adigital** [comment]
Hi Josh,

Hope you're well in these crazy times.

So, we had the great fortune to build the site referenced above just before Craft 3.2 came along and totally broke our front-end editor due to the changes around drafts etc. (I'm sure there's a lesson in here about not recreating core functionality!). We're now in a position that we have the budget and other requests from the client that necessitates getting Craft updated (in addition to just being good practice), which is why I'm adding this comment.

The front end draft editing is working, however I'm bumping up against this change made to Workflow in v. 1.3.0:

> Remove submissions controller and actions, refactoring to service. These shouldn't have been used (not documented), but this removes all workflow/submissions/* actions.

I was previously using that controller, but have now refactored so that the Workflow submissions are made using the [front-end form in your docs](https://verbb.io/craft-plugins/workflow/docs/template-guides/front-end-submission), however the issue with this is that a submitted draft can no longer be updated. I'm open to your suggestions as there may be a way of doing this already with Workflow that I haven't realised (I did experiment with a Reviewer user group but that didn't quite do what is needed), and I can breakdown the process our client wants for their Workflow if this would help.

I wonder how practical it might be to add a new setting for whether a draft should be locked for edits after Workflow submission? I think that change would solve the issue I'm having, and may be useful to others.

Thanks,

Mark

**Comment by engram-design** [comment]
I've just added a new setting for `lockDraftSubmissions` (default to true) that might assist with this? To get this early, change your `verbb/workflow` requirement in `composer.json` to:

```
"require": {
  “verbb/workflow": "dev-craft-3 as 1.5.6",
  "...": "..."
}
```

Then run `composer update`.

**Comment by mark-adigital** [comment]
Amazing - thanks for the super rapid turnaround! That certainly appears to have done the trick, I'll sort out some testing with our client and let you know if we hit any issues.

**Comment by mark-adigital** [comment]
Just to add that the early feedback has been that this has worked great - thanks again.
