### ISSUE TITLE
Error approving new entry

### ISSUE THREAD

**Issue by effer89** [engram-design/Workflow#77]
### Description

Getting `Request missing required body param` when trying to approve an submission.

### Steps to reproduce

1. Approve any submission

### Additional info

- Plugin version: 1.2.1
- Craft version: Craft Pro 3.2.5.1

**Comment by mattrothenberg** [comment]
Confirmed and likely related to https://github.com/verbb/workflow/issues/76.

**Comment by engram-design** [comment]
Should be fixed in [1.2.2](https://github.com/verbb/workflow/releases/tag/1.2.2).

**Comment by martyspain** [comment]
I'm still experiencing this issue on Craft 3.2.8 running Workflow 1.2.2, with existing entries that are Pending. On clicking 'Approve and publish' I get the 'missing body param' error.

**Comment by engram-design** [comment]
@martyspain Can you provide the full error? Struggling to reproduce this no matter what I try!

**Comment by martyspain** [comment]
@engram-design I've just tested approving and publishing an entry again and here's the full error line from our web.log file in production:

`2019-08-08 13:11:50 [-][1][874b3fss90jpk20s4oq15sa9ao][error][yii\web\HttpException:400] yii\web\BadRequestHttpException: Request missing required body param in /var/app/current/vendor/craftcms/cms/src/web/Request.php:656`

I can run an environment up in devMode if you need more information than that?

**Comment by martyspain** [comment]
I've done another test on a draft submitted _after_ the recent update to Workflow 1.2.2 and that can be published with no problems, so maybe my issue is with old Workflow submissions that were created pre-update. Does this help in any way?

**Comment by engram-design** [comment]
@martyspain Ah, yes that helps! I'll see what I can do to scrounge together some examples to test. We've been buffeted around a bit after the latest 3.2.x changes (which changed a few times!)

**Comment by martyspain** [comment]
If you'd like a database dump or any further info, I'm happy to provide whatever help I can! Thanks for looking into this - I realise it's a horrible edge case :)

**Comment by engram-design** [comment]
No need to apologise. Are you on the Discord? If so, my handle is `crawf`. Happy to touch base there as a database dump would be super helpful

**Comment by effer89** [comment]
Still having the same problems :/

> I've done another test on a draft submitted _after_ the recent update to Workflow 1.2.2 and that can be published with no problems, so maybe my issue is with old Workflow submissions that were created pre-update. Does this help in any way?

I have problems approving new workflow entries, not just old ones also.

Thanks!

Plugin version: 1.2.2
Craft version: Craft Pro 3.2.9

**Comment by engram-design** [comment]
Still unable to reproduce on new or existing approvals. @effer89 Would you be able to share the full stack trace error with devMode on?

Can you also let me know the URL that you're trying to approve items on? It should contain at least the `?draftId=x` value.

**Comment by engram-design** [comment]
Should be fixed in [1.2.3](https://github.com/verbb/workflow/releases/tag/1.2.3). Thanks @mattrothenberg for your time with this issue!
